# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lucky/machine_learning/sanskrit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lucky/machine_learning/sanskrit

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucky/machine_learning/sanskrit/CMakeFiles /home/lucky/machine_learning/sanskrit/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucky/machine_learning/sanskrit/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sanskrit

# Build rule for target.
sanskrit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sanskrit
.PHONY : sanskrit

# fast build rule for target.
sanskrit/fast:
	$(MAKE) -f CMakeFiles/sanskrit.dir/build.make CMakeFiles/sanskrit.dir/build
.PHONY : sanskrit/fast

sanskrit.o: sanskrit.cpp.o
.PHONY : sanskrit.o

# target to build an object file
sanskrit.cpp.o:
	$(MAKE) -f CMakeFiles/sanskrit.dir/build.make CMakeFiles/sanskrit.dir/sanskrit.cpp.o
.PHONY : sanskrit.cpp.o

sanskrit.i: sanskrit.cpp.i
.PHONY : sanskrit.i

# target to preprocess a source file
sanskrit.cpp.i:
	$(MAKE) -f CMakeFiles/sanskrit.dir/build.make CMakeFiles/sanskrit.dir/sanskrit.cpp.i
.PHONY : sanskrit.cpp.i

sanskrit.s: sanskrit.cpp.s
.PHONY : sanskrit.s

# target to generate assembly for a file
sanskrit.cpp.s:
	$(MAKE) -f CMakeFiles/sanskrit.dir/build.make CMakeFiles/sanskrit.dir/sanskrit.cpp.s
.PHONY : sanskrit.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sanskrit"
	@echo "... sanskrit.o"
	@echo "... sanskrit.i"
	@echo "... sanskrit.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

